CREATE SCHEMA IF NOT EXISTS school_access;

SET search_path TO school_access;

-- =========================
-- 1. Academic years
-- =========================

CREATE TABLE academic_years (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL,
    starts_on DATE NOT NULL,
    ends_on DATE NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_academic_years_name UNIQUE (name),
    CONSTRAINT chk_academic_years_dates CHECK (starts_on < ends_on)
);

-- =========================
-- 2. Classes
-- =========================

CREATE TABLE classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    academic_year_id BIGINT NOT NULL,
    grade SMALLINT NOT NULL,
    letter VARCHAR(5) NOT NULL,
    name VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_classes_academic_year
        FOREIGN KEY (academic_year_id)
        REFERENCES academic_years (id),

    CONSTRAINT uq_classes_year_grade_letter
        UNIQUE (academic_year_id, grade, letter),

    CONSTRAINT chk_classes_grade
        CHECK (grade BETWEEN 1 AND 12),

    CONSTRAINT chk_classes_status
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX idx_classes_academic_year_id
    ON classes (academic_year_id);

-- =========================
-- 3. Students
-- =========================

CREATE TABLE students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_name VARCHAR(100) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_students_status
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'LEFT_SCHOOL'))
);

CREATE INDEX idx_students_name
    ON students (last_name, first_name);

-- =========================
-- 4. Student class enrollments
-- =========================

CREATE TABLE student_class_enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    class_id BIGINT NOT NULL,
    valid_from DATE NOT NULL,
    valid_to DATE NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_student_class_enrollments_student
        FOREIGN KEY (student_id)
        REFERENCES students (id),

    CONSTRAINT fk_student_class_enrollments_class
        FOREIGN KEY (class_id)
        REFERENCES classes (id),

    CONSTRAINT chk_student_class_enrollments_dates
        CHECK (valid_to IS NULL OR valid_from <= valid_to),

    CONSTRAINT chk_student_class_enrollments_status
        CHECK (status IN ('ACTIVE', 'ENDED'))
);

CREATE INDEX idx_student_class_enrollments_student_id
    ON student_class_enrollments (student_id);

CREATE INDEX idx_student_class_enrollments_class_id
    ON student_class_enrollments (class_id);

CREATE UNIQUE INDEX uq_student_active_class_enrollment
    ON student_class_enrollments (student_id)
    WHERE status = 'ACTIVE';

-- =========================
-- 5. Meal options
-- =========================

CREATE TABLE meal_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL,
    name VARCHAR(100) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_meal_options_code
        UNIQUE (code)
);

-- Recommended seed values, optional for real deployment:
-- STANDARD | Стандартне харчування
-- NO_MEAL  | Не харчується
-- SPECIAL  | Окремий варіант харчування

-- =========================
-- 6. Student meal assignments
-- =========================

CREATE TABLE student_meal_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    meal_option_id BIGINT NOT NULL,
    valid_from DATE NOT NULL,
    valid_to DATE NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_student_meal_assignments_student
        FOREIGN KEY (student_id)
        REFERENCES students (id),

    CONSTRAINT fk_student_meal_assignments_meal_option
        FOREIGN KEY (meal_option_id)
        REFERENCES meal_options (id),

    CONSTRAINT chk_student_meal_assignments_dates
        CHECK (valid_to IS NULL OR valid_from <= valid_to),

    CONSTRAINT chk_student_meal_assignments_status
        CHECK (status IN ('ACTIVE', 'ENDED'))
);

CREATE INDEX idx_student_meal_assignments_student_id
    ON student_meal_assignments (student_id);

CREATE INDEX idx_student_meal_assignments_meal_option_id
    ON student_meal_assignments (meal_option_id);

CREATE UNIQUE INDEX uq_student_active_meal_assignment
    ON student_meal_assignments (student_id)
    WHERE status = 'ACTIVE';

-- =========================
-- 7. RFID cards
-- =========================

CREATE TABLE rfid_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_uid_hash VARCHAR(128) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deactivated_at TIMESTAMP NULL,
    deactivation_reason VARCHAR(30) NULL,

    CONSTRAINT uq_rfid_cards_card_uid_hash
        UNIQUE (card_uid_hash),

    CONSTRAINT chk_rfid_cards_status
        CHECK (status IN ('ACTIVE', 'LOST', 'DAMAGED', 'RETIRED')),

    CONSTRAINT chk_rfid_cards_deactivation_reason
        CHECK (
            deactivation_reason IS NULL
            OR deactivation_reason IN ('LOST', 'DAMAGED', 'REPLACED', 'STUDENT_LEFT', 'OTHER')
        )
);

CREATE INDEX idx_rfid_cards_status
    ON rfid_cards (status);

-- =========================
-- 8. RFID card assignments
-- =========================

CREATE TABLE rfid_card_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    assigned_from DATE NOT NULL,
    assigned_to DATE NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    end_reason VARCHAR(30) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_rfid_card_assignments_card
        FOREIGN KEY (card_id)
        REFERENCES rfid_cards (id),

    CONSTRAINT fk_rfid_card_assignments_student
        FOREIGN KEY (student_id)
        REFERENCES students (id),

    CONSTRAINT chk_rfid_card_assignments_dates
        CHECK (assigned_to IS NULL OR assigned_from <= assigned_to),

    CONSTRAINT chk_rfid_card_assignments_status
        CHECK (status IN ('ACTIVE', 'ENDED')),

    CONSTRAINT chk_rfid_card_assignments_end_reason
        CHECK (
            end_reason IS NULL
            OR end_reason IN ('LOST', 'DAMAGED', 'REPLACED', 'STUDENT_LEFT', 'OTHER')
        )
);

CREATE INDEX idx_rfid_card_assignments_card_id
    ON rfid_card_assignments (card_id);

CREATE INDEX idx_rfid_card_assignments_student_id
    ON rfid_card_assignments (student_id);

CREATE UNIQUE INDEX uq_active_assignment_per_card
    ON rfid_card_assignments (card_id)
    WHERE status = 'ACTIVE';

CREATE UNIQUE INDEX uq_active_assignment_per_student
    ON rfid_card_assignments (student_id)
    WHERE status = 'ACTIVE';

-- =========================
-- 9. Reader locations
-- =========================

CREATE TABLE reader_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_reader_locations_name
        UNIQUE (name)
);

-- Examples:
-- Vestibule
-- Canteen

-- =========================
-- 10. RFID readers
-- =========================

CREATE TABLE rfid_readers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    location_id BIGINT NOT NULL,
    purpose VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_rfid_readers_location
        FOREIGN KEY (location_id)
        REFERENCES reader_locations (id),

    CONSTRAINT uq_rfid_readers_code
        UNIQUE (code),

    CONSTRAINT chk_rfid_readers_purpose
        CHECK (purpose IN ('ENTER_SCHOOL', 'EXIT_SCHOOL', 'MEAL_TAKEN')),

    CONSTRAINT chk_rfid_readers_status
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX idx_rfid_readers_location_id
    ON rfid_readers (location_id);

CREATE INDEX idx_rfid_readers_purpose
    ON rfid_readers (purpose);

-- =========================
-- 11. Access events
-- =========================

CREATE TABLE access_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_time TIMESTAMP NOT NULL,
    event_type VARCHAR(30) NOT NULL,
    event_source VARCHAR(30) NOT NULL,
    event_status VARCHAR(30) NOT NULL,

    reader_id BIGINT NULL,
    scanned_card_uid_hash VARCHAR(128) NULL,

    card_id BIGINT NULL,
    card_assignment_id BIGINT NULL,
    student_id BIGINT NULL,

    notes VARCHAR(255) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_access_events_reader
        FOREIGN KEY (reader_id)
        REFERENCES rfid_readers (id),

    CONSTRAINT fk_access_events_card
        FOREIGN KEY (card_id)
        REFERENCES rfid_cards (id),

    CONSTRAINT fk_access_events_card_assignment
        FOREIGN KEY (card_assignment_id)
        REFERENCES rfid_card_assignments (id),

    CONSTRAINT fk_access_events_student
        FOREIGN KEY (student_id)
        REFERENCES students (id),

    CONSTRAINT chk_access_events_event_type
        CHECK (event_type IN ('ENTER_SCHOOL', 'EXIT_SCHOOL', 'MEAL_TAKEN')),

    CONSTRAINT chk_access_events_event_source
        CHECK (event_source IN ('RFID_READER', 'MANUAL_BY_GUARD')),

    CONSTRAINT chk_access_events_event_status
        CHECK (event_status IN ('VALID', 'UNKNOWN_CARD', 'INACTIVE_CARD', 'NO_ACTIVE_ASSIGNMENT')),

    CONSTRAINT chk_access_events_rfid_fields
        CHECK (
            event_source <> 'RFID_READER'
            OR reader_id IS NOT NULL
        ),

    CONSTRAINT chk_access_events_manual_fields
        CHECK (
            event_source <> 'MANUAL_BY_GUARD'
            OR student_id IS NOT NULL
        )
);

CREATE INDEX idx_access_events_event_time
    ON access_events (event_time);

CREATE INDEX idx_access_events_student_time
    ON access_events (student_id, event_time);

CREATE INDEX idx_access_events_reader_time
    ON access_events (reader_id, event_time);

CREATE INDEX idx_access_events_card_time
    ON access_events (card_id, event_time);

CREATE INDEX idx_access_events_status
    ON access_events (event_status);

CREATE INDEX idx_access_events_scanned_card_uid_hash
    ON access_events (scanned_card_uid_hash);

-- =========================
-- 12. Attendance daily
-- =========================

CREATE TABLE attendance_daily (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attendance_date DATE NOT NULL,
    student_id BIGINT NOT NULL,
    class_id BIGINT NOT NULL,
    first_entry_time TIMESTAMP NOT NULL,
    first_entry_event_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_attendance_daily_student
        FOREIGN KEY (student_id)
        REFERENCES students (id),

    CONSTRAINT fk_attendance_daily_class
        FOREIGN KEY (class_id)
        REFERENCES classes (id),

    CONSTRAINT fk_attendance_daily_first_entry_event
        FOREIGN KEY (first_entry_event_id)
        REFERENCES access_events (id),

    CONSTRAINT uq_attendance_daily_date_student
        UNIQUE (attendance_date, student_id)
);

CREATE INDEX idx_attendance_daily_date
    ON attendance_daily (attendance_date);

CREATE INDEX idx_attendance_daily_class_date
    ON attendance_daily (class_id, attendance_date);

CREATE INDEX idx_attendance_daily_student_date
    ON attendance_daily (student_id, attendance_date);