# Generated by Django 6.0 on 2026-07-18 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MealOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "meal_options",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ReaderLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "db_table": "reader_locations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RfidCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_uid_hash", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("LOST", "Lost"),
                            ("DAMAGED", "Damaged"),
                            ("RETIRED", "Retired"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("deactivation_reason", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "db_table": "rfid_cards",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField()),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "academic_years",
                "ordering": ["-starts_on"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("starts_on__lt", models.F("ends_on"))),
                        name="academic_year_starts_before_ends",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RfidCardAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_from", models.DateTimeField()),
                ("assigned_to", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("ENDED", "Ended")],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                (
                    "end_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOST", "Lost"),
                            ("DAMAGED", "Damaged"),
                            ("REPLACED", "Replaced"),
                            ("STUDENT_LEFT", "Student left"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="school_access.rfidcard",
                    ),
                ),
            ],
            options={
                "db_table": "rfid_card_assignments",
                "ordering": ["-assigned_from"],
            },
        ),
        migrations.CreateModel(
            name="RfidReader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("ENTER_SCHOOL", "Enter school"),
                            ("EXIT_SCHOOL", "Exit school"),
                            ("MEAL_TAKEN", "Meal taken"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="readers",
                        to="school_access.readerlocation",
                    ),
                ),
            ],
            options={
                "db_table": "rfid_readers",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="AccessEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_time", models.DateTimeField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("ENTER_SCHOOL", "Enter school"),
                            ("EXIT_SCHOOL", "Exit school"),
                            ("MEAL_TAKEN", "Meal taken"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "event_source",
                    models.CharField(
                        choices=[
                            ("RFID_READER", "RFID reader"),
                            ("MANUAL_BY_GUARD", "Manual (guard)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "event_status",
                    models.CharField(
                        choices=[
                            ("VALID", "Valid"),
                            ("UNKNOWN_CARD", "Unknown card"),
                            ("INACTIVE_CARD", "Inactive card"),
                            ("NO_ACTIVE_ASSIGNMENT", "No active assignment"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "scanned_card_uid_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="school_access.rfidcard",
                    ),
                ),
                (
                    "card_assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="school_access.rfidcardassignment",
                    ),
                ),
                (
                    "reader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="school_access.rfidreader",
                    ),
                ),
            ],
            options={
                "db_table": "access_events",
                "ordering": ["-event_time"],
            },
        ),
        migrations.CreateModel(
            name="SchoolClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.PositiveSmallIntegerField()),
                ("letter", models.CharField(max_length=8)),
                ("name", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classes",
                        to="school_access.academicyear",
                    ),
                ),
            ],
            options={
                "db_table": "classes",
                "ordering": ["grade", "letter"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("LEFT_SCHOOL", "Left school"),
                        ],
                        default="ACTIVE",
                        max_length=15,
                    ),
                ),
            ],
            options={
                "db_table": "students",
                "ordering": ["last_name", "first_name"],
                "indexes": [
                    models.Index(
                        fields=["last_name", "first_name"], name="idx_students_name"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="rfidcardassignment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="card_assignments",
                to="school_access.student",
            ),
        ),
        migrations.CreateModel(
            name="AttendanceDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attendance_date", models.DateField()),
                ("first_entry_time", models.DateTimeField()),
                (
                    "first_entry_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="school_access.accessevent",
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_records",
                        to="school_access.schoolclass",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="school_access.student",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_daily",
                "ordering": ["-attendance_date"],
            },
        ),
        migrations.AddField(
            model_name="accessevent",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="access_events",
                to="school_access.student",
            ),
        ),
        migrations.CreateModel(
            name="StudentClassEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("ENDED", "Ended")],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="school_access.schoolclass",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_enrollments",
                        to="school_access.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_class_enrollments",
                "ordering": ["-valid_from"],
            },
        ),
        migrations.CreateModel(
            name="StudentMealAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("ENDED", "Ended")],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                (
                    "meal_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="school_access.mealoption",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_assignments",
                        to="school_access.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_meal_assignments",
                "ordering": ["-valid_from"],
            },
        ),
        migrations.AddIndex(
            model_name="schoolclass",
            index=models.Index(
                fields=["academic_year"], name="idx_classes_academic_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolclass",
            constraint=models.UniqueConstraint(
                fields=("academic_year", "grade", "letter"),
                name="unique_class_per_academic_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="rfidcardassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("card",),
                name="unique_active_assignment_per_card",
            ),
        ),
        migrations.AddConstraint(
            model_name="rfidcardassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("student",),
                name="unique_active_assignment_per_student",
            ),
        ),
        migrations.AddIndex(
            model_name="attendancedaily",
            index=models.Index(fields=["attendance_date"], name="idx_attendance_date"),
        ),
        migrations.AddIndex(
            model_name="attendancedaily",
            index=models.Index(
                fields=["school_class", "attendance_date"],
                name="idx_attendance_class_date",
            ),
        ),
        migrations.AddIndex(
            model_name="attendancedaily",
            index=models.Index(
                fields=["student", "attendance_date"],
                name="idx_attendance_student_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancedaily",
            constraint=models.UniqueConstraint(
                fields=("attendance_date", "student"), name="unique_attendance_per_day"
            ),
        ),
        migrations.AddIndex(
            model_name="accessevent",
            index=models.Index(fields=["event_time"], name="idx_events_time"),
        ),
        migrations.AddIndex(
            model_name="accessevent",
            index=models.Index(
                fields=["student", "event_time"], name="idx_events_student_time"
            ),
        ),
        migrations.AddIndex(
            model_name="accessevent",
            index=models.Index(
                fields=["reader", "event_time"], name="idx_events_reader_time"
            ),
        ),
        migrations.AddIndex(
            model_name="accessevent",
            index=models.Index(
                fields=["card", "event_time"], name="idx_events_card_time"
            ),
        ),
        migrations.AddIndex(
            model_name="accessevent",
            index=models.Index(
                fields=["scanned_card_uid_hash"], name="idx_events_scanned_hash"
            ),
        ),
        migrations.AddIndex(
            model_name="studentclassenrollment",
            index=models.Index(fields=["school_class"], name="idx_enrollments_class"),
        ),
        migrations.AddConstraint(
            model_name="studentclassenrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("student",),
                name="unique_active_class_enrollment_per_student",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentmealassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("student",),
                name="unique_active_meal_assignment_per_student",
            ),
        ),
    ]
