# Generated by Django 6.0 on 2026-07-18 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.RunSQL(
            sql="CREATE SCHEMA IF NOT EXISTS school_access;",
            reverse_sql="DROP SCHEMA IF EXISTS school_access CASCADE;",
        ),
        migrations.CreateModel(
            name="MealOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": '"school_access"."meal_options"',
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ReaderLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": '"school_access"."reader_locations"',
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField()),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": '"school_access"."academic_years"',
                "ordering": ["-starts_on"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("starts_on__lt", models.F("ends_on"))),
                        name="chk_academic_years_dates",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RfidCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_uid_hash", models.CharField(max_length=128, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("LOST", "Lost"),
                            ("DAMAGED", "Damaged"),
                            ("RETIRED", "Retired"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deactivation_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOST", "Lost"),
                            ("DAMAGED", "Damaged"),
                            ("REPLACED", "Replaced"),
                            ("STUDENT_LEFT", "Student left"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": '"school_access"."rfid_cards"',
                "ordering": ["-id"],
                "indexes": [
                    models.Index(fields=["status"], name="idx_rfid_cards_status")
                ],
            },
        ),
        migrations.CreateModel(
            name="RfidCardAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_from", models.DateField()),
                ("assigned_to", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("ENDED", "Ended")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "end_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOST", "Lost"),
                            ("DAMAGED", "Damaged"),
                            ("REPLACED", "Replaced"),
                            ("STUDENT_LEFT", "Student left"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="school_access.rfidcard",
                    ),
                ),
            ],
            options={
                "db_table": '"school_access"."rfid_card_assignments"',
                "ordering": ["-assigned_from"],
            },
        ),
        migrations.CreateModel(
            name="RfidReader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("ENTER_SCHOOL", "Enter school"),
                            ("EXIT_SCHOOL", "Exit school"),
                            ("MEAL_TAKEN", "Meal taken"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="readers",
                        to="school_access.readerlocation",
                    ),
                ),
            ],
            options={
                "db_table": '"school_access"."rfid_readers"',
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="AccessEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_time", models.DateTimeField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("ENTER_SCHOOL", "Enter school"),
                            ("EXIT_SCHOOL", "Exit school"),
                            ("MEAL_TAKEN", "Meal taken"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "event_source",
                    models.CharField(
                        choices=[
                            ("RFID_READER", "RFID reader"),
                            ("MANUAL_BY_GUARD", "Manual (guard)"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "event_status",
                    models.CharField(
                        choices=[
                            ("VALID", "Valid"),
                            ("UNKNOWN_CARD", "Unknown card"),
                            ("INACTIVE_CARD", "Inactive card"),
                            ("NO_ACTIVE_ASSIGNMENT", "No active assignment"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "scanned_card_uid_hash",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("notes", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="school_access.rfidcard",
                    ),
                ),
                (
                    "card_assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="school_access.rfidcardassignment",
                    ),
                ),
                (
                    "reader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="school_access.rfidreader",
                    ),
                ),
            ],
            options={
                "db_table": '"school_access"."access_events"',
                "ordering": ["-event_time"],
            },
        ),
        migrations.CreateModel(
            name="SchoolClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.PositiveSmallIntegerField()),
                ("letter", models.CharField(max_length=5)),
                ("name", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classes",
                        to="school_access.academicyear",
                    ),
                ),
            ],
            options={
                "db_table": '"school_access"."classes"',
                "ordering": ["grade", "letter"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("LEFT_SCHOOL", "Left school"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": '"school_access"."students"',
                "ordering": ["last_name", "first_name"],
                "indexes": [
                    models.Index(
                        fields=["last_name", "first_name"], name="idx_students_name"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="rfidcardassignment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="card_assignments",
                to="school_access.student",
            ),
        ),
        migrations.CreateModel(
            name="AttendanceDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attendance_date", models.DateField()),
                ("first_entry_time", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "first_entry_event",
                    models.ForeignKey(
                        db_column="first_entry_event_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="school_access.accessevent",
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        db_column="class_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_records",
                        to="school_access.schoolclass",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="school_access.student",
                    ),
                ),
            ],
            options={
                "db_table": '"school_access"."attendance_daily"',
                "ordering": ["-attendance_date"],
            },
        ),
        migrations.AddField(
            model_name="accessevent",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="access_events",
                to="school_access.student",
            ),
        ),
        migrations.CreateModel(
            name="StudentClassEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("ENDED", "Ended")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school_class",
                    models.ForeignKey(
                        db_column="class_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="school_access.schoolclass",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_enrollments",
                        to="school_access.student",
                    ),
                ),
            ],
            options={
                "db_table": '"school_access"."student_class_enrollments"',
                "ordering": ["-valid_from"],
            },
        ),
        migrations.CreateModel(
            name="StudentMealAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("ENDED", "Ended")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meal_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="school_access.mealoption",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_assignments",
                        to="school_access.student",
                    ),
                ),
            ],
            options={
                "db_table": '"school_access"."student_meal_assignments"',
                "ordering": ["-valid_from"],
            },
        ),
        migrations.AddIndex(
            model_name="rfidreader",
            index=models.Index(
                fields=["location"], name="idx_rfid_readers_location_id"
            ),
        ),
        migrations.AddIndex(
            model_name="rfidreader",
            index=models.Index(fields=["purpose"], name="idx_rfid_readers_purpose"),
        ),
        migrations.AddIndex(
            model_name="schoolclass",
            index=models.Index(
                fields=["academic_year"], name="idx_classes_academic_year_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolclass",
            constraint=models.UniqueConstraint(
                fields=("academic_year", "grade", "letter"),
                name="uq_classes_year_grade_letter",
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolclass",
            constraint=models.CheckConstraint(
                condition=models.Q(("grade__gte", 1), ("grade__lte", 12)),
                name="chk_classes_grade",
            ),
        ),
        migrations.AddIndex(
            model_name="rfidcardassignment",
            index=models.Index(fields=["card"], name="idx_rca_card_id"),
        ),
        migrations.AddIndex(
            model_name="rfidcardassignment",
            index=models.Index(fields=["student"], name="idx_rca_student_id"),
        ),
        migrations.AddConstraint(
            model_name="rfidcardassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("card",),
                name="uq_active_assignment_per_card",
            ),
        ),
        migrations.AddConstraint(
            model_name="rfidcardassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("student",),
                name="uq_active_assignment_per_student",
            ),
        ),
        migrations.AddConstraint(
            model_name="rfidcardassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("assigned_to__isnull", True),
                    ("assigned_to__gte", models.F("assigned_from")),
                    _connector="OR",
                ),
                name="chk_rfid_card_assignments_dates",
            ),
        ),
        migrations.AddIndex(
            model_name="attendancedaily",
            index=models.Index(
                fields=["attendance_date"], name="idx_attendance_daily_date"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancedaily",
            index=models.Index(
                fields=["school_class", "attendance_date"],
                name="idx_att_daily_class_date",
            ),
        ),
        migrations.AddIndex(
            model_name="attendancedaily",
            index=models.Index(
                fields=["student", "attendance_date"], name="idx_att_daily_student_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancedaily",
            constraint=models.UniqueConstraint(
                fields=("attendance_date", "student"),
                name="uq_attendance_daily_date_student",
            ),
        ),
        migrations.AddIndex(
            model_name="accessevent",
            index=models.Index(
                fields=["event_time"], name="idx_access_events_event_time"
            ),
        ),
        migrations.AddIndex(
            model_name="accessevent",
            index=models.Index(
                fields=["student", "event_time"], name="idx_access_events_student_time"
            ),
        ),
        migrations.AddIndex(
            model_name="accessevent",
            index=models.Index(
                fields=["reader", "event_time"], name="idx_access_events_reader_time"
            ),
        ),
        migrations.AddIndex(
            model_name="accessevent",
            index=models.Index(
                fields=["card", "event_time"], name="idx_access_events_card_time"
            ),
        ),
        migrations.AddIndex(
            model_name="accessevent",
            index=models.Index(
                fields=["event_status"], name="idx_access_events_status"
            ),
        ),
        migrations.AddIndex(
            model_name="accessevent",
            index=models.Index(
                fields=["scanned_card_uid_hash"], name="idx_access_events_uid_hash"
            ),
        ),
        migrations.AddConstraint(
            model_name="accessevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("event_source", "RFID_READER"), _negated=True),
                    ("reader__isnull", False),
                    _connector="OR",
                ),
                name="chk_access_events_rfid_fields",
            ),
        ),
        migrations.AddConstraint(
            model_name="accessevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("event_source", "MANUAL_BY_GUARD"), _negated=True),
                    ("student__isnull", False),
                    _connector="OR",
                ),
                name="chk_access_events_manual_fields",
            ),
        ),
        migrations.AddIndex(
            model_name="studentclassenrollment",
            index=models.Index(fields=["student"], name="idx_sce_student_id"),
        ),
        migrations.AddIndex(
            model_name="studentclassenrollment",
            index=models.Index(fields=["school_class"], name="idx_sce_class_id"),
        ),
        migrations.AddConstraint(
            model_name="studentclassenrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("student",),
                name="uq_student_active_class_enrollment",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentclassenrollment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_to__isnull", True),
                    ("valid_to__gte", models.F("valid_from")),
                    _connector="OR",
                ),
                name="chk_student_class_enrollments_dates",
            ),
        ),
        migrations.AddIndex(
            model_name="studentmealassignment",
            index=models.Index(fields=["student"], name="idx_sma_student_id"),
        ),
        migrations.AddIndex(
            model_name="studentmealassignment",
            index=models.Index(fields=["meal_option"], name="idx_sma_meal_id"),
        ),
        migrations.AddConstraint(
            model_name="studentmealassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("student",),
                name="uq_student_active_meal_assignment",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentmealassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_to__isnull", True),
                    ("valid_to__gte", models.F("valid_from")),
                    _connector="OR",
                ),
                name="chk_student_meal_assignments_dates",
            ),
        ),
    ]
