# Generated by Django 6.0 on 2026-07-18 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_access", "0002_seed_dictionaries"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessevent",
            name="reader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="school_access.rfidreader",
            ),
        ),
        migrations.AlterField(
            model_name="accessevent",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="access_events",
                to="school_access.student",
            ),
        ),
    ]
