# Generated by Django 6.0 on 2026-08-06 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_access", "0003_alter_accessevent_reader_alter_accessevent_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancedaily",
            name="last_exit_event",
            field=models.ForeignKey(
                blank=True,
                db_column="last_exit_event_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="school_access.accessevent",
            ),
        ),
        migrations.AddField(
            model_name="attendancedaily",
            name="last_exit_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accessevent",
            name="event_source",
            field=models.CharField(
                choices=[
                    ("RFID_READER", "RFID-зчитувач"),
                    ("MANUAL_BY_GUARD", "Вручну (охорона)"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="accessevent",
            name="event_status",
            field=models.CharField(
                choices=[
                    ("VALID", "Дійсний"),
                    ("UNKNOWN_CARD", "Невідома картка"),
                    ("INACTIVE_CARD", "Неактивна картка"),
                    ("NO_ACTIVE_ASSIGNMENT", "Немає активної прив'язки"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="accessevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("ENTER_SCHOOL", "Вхід до школи"),
                    ("EXIT_SCHOOL", "Вихід зі школи"),
                    ("MEAL_TAKEN", "Отримання харчування"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="rfidcard",
            name="deactivation_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LOST", "Загублена"),
                    ("DAMAGED", "Пошкоджена"),
                    ("REPLACED", "Замінена"),
                    ("STUDENT_LEFT", "Учень вибув"),
                    ("OTHER", "Інше"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rfidcard",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Активна"),
                    ("LOST", "Загублена"),
                    ("DAMAGED", "Пошкоджена"),
                    ("RETIRED", "Списана"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="rfidcardassignment",
            name="end_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LOST", "Загублена"),
                    ("DAMAGED", "Пошкоджена"),
                    ("REPLACED", "Замінена"),
                    ("STUDENT_LEFT", "Учень вибув"),
                    ("OTHER", "Інше"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rfidcardassignment",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Активний"), ("ENDED", "Завершений")],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="rfidreader",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("ENTER_SCHOOL", "Вхід до школи"),
                    ("EXIT_SCHOOL", "Вихід зі школи"),
                    ("MEAL_TAKEN", "Отримання харчування"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="rfidreader",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Активний"), ("INACTIVE", "Неактивний")],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="schoolclass",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Активний"), ("INACTIVE", "Неактивний")],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Активний"),
                    ("INACTIVE", "Неактивний"),
                    ("LEFT_SCHOOL", "Вибув"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="studentclassenrollment",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Активний"), ("ENDED", "Завершений")],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="studentmealassignment",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Активний"), ("ENDED", "Завершений")],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
