# Generated by Django 6.0 on 2026-08-06 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_access", "0004_attendancedaily_last_exit_event_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancedaily",
            name="last_entry_event",
            field=models.ForeignKey(
                blank=True,
                db_column="last_entry_event_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="school_access.accessevent",
            ),
        ),
        migrations.AddField(
            model_name="attendancedaily",
            name="last_entry_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
